---
name: Linting

on:
  pull_request:

jobs:
  crds:
    name: CRDs up-to-date
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Run make manifests to update CRDs
        run: make manifests
      - name: Validate that nothing has changed
        run: git add -A && git diff --staged --exit-code

  dco:
    name: DCO in Commit Message(s)
    runs-on: ubuntu-latest
    steps:
      - name: Get PR commits
        id: 'get-pr-commits'
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run DCO check
        uses: tim-actions/dco@master
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}

  gitlint:
    name: Commit Message(s)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run gitlint
        run: make gitlint

  golangci-lint:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Run golangci-lint
        run: make golangci-lint

  headers:
    name: License Headers
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Check License Headers
        uses: nilp0inter/search-legal-headers@v0.1.0

  markdown-link-check:
    name: Markdown Links (modified files)
    runs-on: ubuntu-latest
    env:
      BASE_BRANCH: ${{ github.base_ref }}
      FILE_EXTENSION: .md
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Extract markdown from CSV.yaml
        run: |-
          sudo snap install yq --channel=v4/stable && \
          yq e '.spec.description, .spec.links' config/manifests/bases/submariner.clusterserviceversion.yaml > extracted_yaml_links.md
      - name: Prepare a list of md files
        run: |-
          git fetch origin "${BASE_BRANCH}" --depth=1 > /dev/null
          MASTER_HASH=$(git rev-parse origin/"${BASE_BRANCH}")
          mapfile -t FILE_ARRAY < <( git diff --name-only --diff-filter=AM "$MASTER_HASH" )
          for i in "${FILE_ARRAY[@]}"; do
            if [ "${i##*.}" == "${FILE_EXTENSION#.}" ]; then
              MD_FILES="${MD_FILES}${i},"
            fi
          done
          export MD_FILES="${MD_FILES}extracted_yaml_links.md"
          echo "MD_FILES=${MD_FILES}" >> $GITHUB_ENV
      - name: Run markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: ".markdownlinkcheck.json"
          check-modified-files-only: "no"
          file-path: ${{ env.MD_FILES }}

  markdownlint:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Run markdownlint
        run: make markdownlint

  yaml-lint:
    name: YAML
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Run yamllint
        run: make yamllint
